image: mlaurie/aws-angular-builder:1.4.9

pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches' ."
  branches:
    master:
    - step:
        deployment: production
        script:
          - npm install
          - ng build --prod --env=prod
          - aws s3 sync dist s3://productx-vendorportal --delete --cache-control "no-cache"
    production-stage:
    - step:
        deployment: production
        script:
          - npm install
          - ng build --prod --env=prod-stage
          - aws s3 sync dist s3://productx-vendorportal-production-stage --delete --cache-control "no-cache"
    staging:
    - step:
        deployment: staging
        script:
          - npm install
          - npm i node-sass@4.8.1
          - ng build --prod --env=zyto-stage --build-optimizer=false
          - aws s3 sync dist s3://productx-vendorportal-staging --delete --cache-control "no-cache"
    develop:
    - step:
        deployment: test
        script:
          - npm install
          - npm i node-sass@4.8.1
          - ng build --prod --env=zyto-test --build-optimizer=false
          - aws s3 sync dist s3://productx-vendorportal-testing --delete --cache-control "no-cache"
